loan-app/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  resources :loans

end

loan-app/app/models/loan.rb
class Loan < ActiveRecord::Base
	validates :giver, :sum, :term, :interest, presence: true
end

loan-app/app/models/user.rb
class User < ActiveRecord::Base
	validates :name, :lastname, {presence: true, length: {minimum: 2, maximum: 20}}
	validates :password, :password_confirmation, {presence: true, length: {minimum: 6, maximum: 20}}
	has_secure_password
end

loan-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

loan-app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
  	if user && user.authenticate(params[:user])
  		log_in
  	else
  		render 'new'
  	end
  end
end

loan-app/app/controllers/user_controller.rb
class UserController < ApplicationController
end

loan-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@user_hash = User.order(params[:sort]).paginate(per_page: 5, page: params[:page])
    if params[:sort].nil?
      @sort = "created_at"
    else
      @sort = params[:sort]
    end
  	@admin_user = params[:name]

  end

  def show
  	@name = User.find(params[:id])
  end
  def new
  	@user = User.new
  end

  def create
  	  @user = User.create(name: params[:user][:name], lastname: params[:user][:lastname], password: params[:user][:password], password_confirmation: params[:user][:password_confirmation])
      if @user.errors.empty?
        redirect_to "index"
      else
        render "new"
      end
  	  
  end
end

loan-app/app/helpers/application_helper.rb
module ApplicationHelper
end

loan-app/app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	def logged_in?
		!current_user.nil?
	end
end

loan-app/app/helpers/user_helper.rb
module UserHelper
end

loan-app/app/helpers/users_helper.rb
module UsersHelper
end

loan-app/app/views/layouts/_errors.html.erb
<% if @user.errors.any? %>
	<div class="alert alert-warning alert-dismissable">
		<a class="close" href="#" data-dismiss="alert">&times</a>
		<ul>
			<% @user.errors.full_messages.each do |m| %>
			<li><%= m %></li>
			<% end %>
		</ul>
	</div>
<% end %>

loan-app/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <% if logged_in? %>
              <%= current_user.name %>
              <% else %>
              login
            <% end %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

loan-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Create yuor loan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">

	</div>
<%= render "layouts/navigation" %>
<%= yield %>

</body>
</html>

loan-app/app/views/users/index.html.erb
<h1><%= @admin_user %></h1>
<p><%= link_to "By name", users_path(sort: "name") %></p>
<table class = "table table-striped">
	<tr>
		<td>id</td><td>name<%= link_to "↑", users_path(sort: "name ASC") %><%= link_to "↓", users_path(sort: "name DESC") %></td><td>last name<%= link_to "↑", users_path(sort: "lastname ASC") %><%= link_to "↓", users_path(sort: "lastname DESC") %></td>
	</tr>
	<% @user_hash.each do |user| %>
	<tr>
		<td><%= user[:id]%></td>
		<td><%= user[:name]%></td>
		<td><%= user[:lastname]%></td>
	</tr>
	<% end %>

</table>
<%= will_paginate @user_hash %>

loan-app/app/views/users/new.html.erb
<%= render "layouts/errors" %>
<%= form_for @user do |f| %>
	<%= f.text_field :name %>
	<%= f.text_field :lastname %>
	<%= f.text_field :password %>
	<%= f.text_field :password_confirmation %>
	<%= f.submit %>

<% end %>

loan-app/app/views/users/show.html.erb
<h1></h1>
<% %>
<p>My name is <%= @name %></p>
<p><%= link_to "Users_list", users_path%></p>